# MAP DATA ###
# 48 WIDE
# 29 DOWN



class maps:

    def __init__(self):

        # TEMPLATE
        self.map0 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map1 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              e",
"w                     wwww                     e",
"w                      ww                      e",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w              wwwwwwwwwwwwwwwwww              w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                E     w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                     wwww                     w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",

            ]
        self.map2 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w           E        E                         w",
"w   E                                          w",
"w            wwwwwwwwwwwwwwwwwwwww      ww     w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                          P     w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w    E       ww       wwwwwwwwwwwwwwwwwwwwwwwwww",
"w            ww       ww                       e",
"w        wwwwwwwwwwwwwww  E  E                 e",
"w        wwwwwwwwwwwwwww    E                  e",
"w        ww           ww                       w",
"w    E   ww           ww                       w",
"w        ww   E E E   wwwwwwwwwwww             w",
"w        ww           wwwwwwwwwwww             w",
"w        ww              w                     w",
"w                    E   w                     w",
"w            E           w                     w",
"w                        w                     w",
"wwwwwwwwwwwwwwww     wwwww         www         w",
"w                                              w",
"w    E                              E          w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map3 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w   E                    E                     w",
"w                                              w",
"w          wwwwwwwwwwwwwwwwwwwwwwwww           w",
"w                                 ww           w",
"w                                 ww           w",
"wwwwwwwwww         E      E       ww           w",
"wwwwwwwwwwww                      ww           w",
"wwwwwwwwwwwwwwwwwwwwwwwwww        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww             E       w        ww           w",
"wwww                     w   E    ww           w",
"wwww          ww         w        ww           w",
"wwww    E     ww         w        ww           w",
"wwww          ww    E    w        ww     P     w",
"e             ww         w        ww           w",
"e             ww         w        wwwwwwwwwwwwww",
"e             ww         w                     w",
"e             ww         w                     w",
"wwwwwwwwwwwwwwww         w        E            w",
"wwwwwwwwwwwwwwww         w                     w",
"w                        wwwwwwwwwwww     E    w",
"w                                              w",
"w      E            E            E             w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",

            ]

        self.map4 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                       wwwwwwwwwwwwwwwwwwwwwwww",
"w          E                                   w",
"w                         E                    w",
"w                                    E         w",
"w    wwwwwwwwwwwwwwwww                         w",
"w    w               wwwwwwwwwwwww             w",
"w    w                                  E      w",
"w    w    E           E                        w",
"w    w                                         w",
"w    w                                         w",
"w    w       wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w    w       w                                 w",
"w    w   E   w           E              E      w",
"w    w       w      wwwwwwwwwwwwwwwwwwww       w",
"w    w       w      w                  w       w",
"w    w              w        E         w       w",
"w    w          E   w                          w",
"w    w              w                          w",
"w    w       wwwwwwww      wwwwwwww   E        w",
"w    w       ww                   w            w",
"w    w   E   ww                   w        E   w",
"w P  w   E   ww              E    w            w",
"wwwwww       ww                   w            w",
"weeeewwwwwwwwww        wwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                E                      E      w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",

            ]
        self.map5 = [
            
"wwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww E            E wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww       P        wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwww                wwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",


        ]

        self.map6 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                      B                       w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                     P                        w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",

            ]
