# MAP DATA ###
# 48 WIDE
# 29 DOWN



class maps:

    def __init__(self):

        # TEMPLATE

        self.map0 = [

"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
            ]

        self.map1 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                             ee",
"w                     wwww                    ee",
"w                                              e",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w              wwwwwwwwwwwwwwwwww              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                     wwww                     w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]
        self.map2 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwww                                       w",
"wwwwww                                         w",
"wwww                                           w",
"ww           ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww       wwwwwwwwwwwwwwwwwwwwwwwwww",
"w            ww       wwwwwwwwwwwwwwwwwwwwwwwwww",
"w            ww       ww                      ee",
"w        wwwwwwwwwwwwwww                      ee",
"w        wwwwwwwwwwwwwww                      ee",
"w        ww           ww                      ww",
"w        ww           ww                       w",
"w        ww           wwwwwwwwwwww             w",
"w        ww           wwwwwwwwwwww             w",
"w        ww                                    w",
"w        ww                                    w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwww                         w",
"wwwwwwwwwwwwwwwwwwwwww                         w",
"wpgy                                           w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map3 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w          wwwwwwwwwwwwwwwwwwwwwwwww           w",
"w                                 ww           w",
"w                                 ww           w",
"w                                 ww           w",
"w                                 ww           w",
"wwwwwwwwwwwww                     ww           w",
"wwwwwwwwwwwww                     ww           w",
"wwwwwwwwwwwwwwwwwwwwwwwwww        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww          ww         w        ww           w",
"wwww          ww         w        ww           w",
"wwww          ww         w        ww           w",
"wwww          ww         w        ww           w",
"e             ww         w        wwwwwwwwwwwwww",
"e             ww         w                     w",
"e             ww         w                     w",
"wwwwwwwwwwwwwwww         w                     w",
"wwwwwwwwwwwwwwww         w                     w",
"w                        w                     w",
"w                        w                     w",
"w        wwwwwwwwwwwwwwwwwwwww                 w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map0 = [

"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
            ]
        self.map0 = [

"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
            ]
