# MAP DATA ###
# 48 WIDE
# 29 DOWN



class maps:

    def __init__(self):

        # TEMPLATE
        self.map0 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map1 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              e",
"w                     wwww                     e",
"w                      ww                      e",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w              wwwwwwwwwwwwwwwwww              w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                      ww                      w",
"w                     wwww                     w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]
        self.map2 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w            wwwwwwwwwwwwwwwwwwwww      ww     w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww                                w",
"w            ww       wwwwwwwwwwwwwwwwwwwwwwwwww",
"w            ww       ww                       e",
"w        wwwwwwwwwwwwwww                       e",
"w        wwwwwwwwwwwwwww                       e",
"w        ww           ww                       w",
"w        ww           ww                       w",
"w        ww           wwwwwwwwwwww             w",
"w        ww           wwwwwwwwwwww             w",
"w        ww              w                     w",
"w                        w                     w",
"w                        w                     w",
"w                        w                     w",
"wwwwwwwwwwwwwwww     wwwww         www         w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map3 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w          wwwwwwwwwwwwwwwwwwwwwwwww           w",
"w                                 ww           w",
"w                                 ww           w",
"wwwwwwwwww                        ww           w",
"wwwwwwwwwwww                      ww           w",
"wwwwwwwwwwwwwwwwwwwwwwwwww        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww                     w        ww           w",
"wwww          ww         w        ww           w",
"wwww          ww         w        ww           w",
"wwww          ww         w        ww           w",
"e             ww         w        ww           w",
"e             ww         w        wwwwwwwwwwwwww",
"e             ww         w                     w",
"e             ww         w                     w",
"wwwwwwwwwwwwwwww         w                     w",
"wwwwwwwwwwwwwwww         w                     w",
"w                        wwwwwwwwwwww          w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]

        self.map4 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                       wwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w    wwwwwwwwwwwwwwwww                         w",
"w    w               wwwwwwwwwwwww             w",
"w    w                           w             w",
"w    w                           w             w",
"w    w                           w             w",
"w    w                           w             w",
"w    w             wwwwwwwwwwwwwww             w",
"w    w             w                           w",
"w    w      w      w                           w",
"w    w      w      w                           w",
"w    w      w      w                           w",
"w    w      w      w       w                   w",
"w    w             w       w                   w",
"w    w             w       w                   w",
"w    w        wwwwww       wwwwwwww            w",
"w    w        w                   wwwwwwwwwwwwww",
"w    w        w                   w            w",
"w    w        w                   w            w",
"wwwwww        w                   w            w",
"weeeewwwwwwwwww        wwwwwwwwwwww            w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]
        self.map5 = [

"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w               wwwwwwwwwwwwwwwwwwwww          e",
"w                                              e",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"w                                              w",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            ]
